name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true -p:AssemblyName=TodoApp -o ./publish

    - name: List publish directory
      run: dir ./publish
  
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TodoApp
        path: ./publish/*.exe
